### ISSUE TITLE
feat: delete this skid

### ISSUE THREAD

**Issue by jesterwoohoo** [liquidsquid1/simplebounce#19]
### Describe your feature request.

most themes are found on github now by searching “LiquidBounce theme”, and the rest of them are unfinished so no need for this repo to be up tbh lucas’ themes can be found on their github (which was termed but it is getting appealed) and my themes can be found (quite shocking) on my github, or by searching liquidbounce theme. if they aren’t compiled, it’s for a reason (like my riselb theme not being finished) so having a collection of colours that people could easily download was not in the list of things i wanted for that theme.

### Additional context

most themes are found on github now by searching “LiquidBounce theme”, and the rest of them are unfinished so no need for this repo to be up tbh lucas’ themes can be found on their github (which was termed but it is getting appealed) and my themes can be found (quite shocking) on my github, or by searching liquidbounce theme. if they aren’t compiled, it’s for a reason (like my riselb theme not being finished) so having a collection of colours that people could easily download was not in the list of things i wanted for that theme.

**Comment by liquidsquid1** [comment]
we can stop with this now
