### ISSUE TITLE
bug: theme is not theming

### ISSUE THREAD

**Issue by OfficialError** [liquidsquid1/simplebounce#20]
### LiquidBounce Build/Version

2134

### Operating System

macOS, Linux, Windows 7, Windows 8, Windows 8.1, Windows 10, Windows 11

### Minecraft Version

1.13

### Simplebounce Version

1

### Describe the bug

it no apply when .client theme simple after compile !
client say no thank

### Steps to reproduce

cone
coppinle
cpoy
.client theme simple
wait 1s

**Comment by jesterwoohoo** [comment]
why me no work i swear this is skid from night x and fdp this noob no knowhting

**Comment by liquidsquid1** [comment]
> ### LiquidBounce Build/Version
> 2134
> 
> ### Operating System
> macOS, Linux, Windows 7, Windows 8, Windows 8.1, Windows 10, Windows 11
> 
> ### Minecraft Version
> 1.13
> 
> ### Simplebounce Version
> 1
> 
> ### Describe the bug
> it no apply when .client theme simple after compile ! client say no thank
> 
> ### Steps to reproduce
> cone coppinle cpoy .client theme simple wait 1s
> 
> ### Screenshots
> _No response_

this is because nextgen wasn’t made for 1.13, update to the newest version!

**Comment by jesterwoohoo** [comment]
no
