### ISSUE TITLE
[?] what is your opinion on https://en.wikipedia.org/wiki/Freedom_Party_of_Austria

### ISSUE THREAD

**Issue by jesterwoohoo** [liquidsquid1/simplebounce#22]
### Question

https://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austriahttps://en.wikipedia.org/wiki/Freedom_Party_of_Austria

**Comment by liquidsquid1** [comment]
can we stick these offtopic conversations elsewhere and not on my repo 🙏
